POST http://localhost:3000/api/fashion
Content-Type: application/json

{
    "eMail": "mail@gmail.com",
    "password": "ASDgdsf55 "
}

###

POST http://localhost:3000/api/LogIn
Content-Type: application/json

{
    "name": "mail@gmail.com",
    "password": "ASDgdsf55 "
}


###
GET http://localhost:3000/api/fashionCP
Authorization:bearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjg3ODA3NjgyLCJleHAiOjE2ODc5ODA0ODJ9.xqh224SIY62hi7IAjUPJLWYaKDCMZufOFEbzLVg7G2c